FROM python:3.9-slim-bullseye

WORKDIR /app

# Install any system dependencies (e.g., if you use serial ports)
RUN apt-get update && apt-get install -y \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Copy your specific project files
COPY /CT6B/CT6B_websocket_TinyTVLx_Recevier/ .

# Install python dependencies
RUN pip install websockets pyserial aiohttp

# Match your systemd env variable
ENV PYTHONUNBUFFERED=1

CMD ["python3", "main_client.py"]		
